# List all the just commands
default:
    @just --list

# Enter a shell session which has all the necessary tools for this flake
[linux]
test:
  nix build ".#nixosConfigurations.storm.config.system.build.toplevel" --show-trace --verbose