[accessibility]
# Content scale for panels and other non-bar shell UI.
ui_scale = 1.1

[shell]
font_family = "JetBrains Mono"

[theme]
mode = "dark"
source = "custom"
custom_palette = "GruvboxDarkHard"

[theme.templates]
enable_builtin_templates = true
builtin_ids = ["gtk3", "gtk4"]

[bar.main]
position = "top"
thickness = 28
background_opacity = 0.2
margin_ends = 6
margin_edge = 2
widget_spacing = 4
font_family = "JetBrains Mono"
font_weight = 400
shadow = false
hover_highlight = false
start = ["group:system"]
center = ["group:clock"]
end = ["group:controls"]

[[bar.main.capsule_group]]
id = "system"
members = ["workspaces"]
fill = "#141414"
foreground = "#ffffff"
opacity = 0.5
padding = 10
radius = 10
widget_spacing = 4

[[bar.main.capsule_group]]
id = "clock"
members = ["clock"]
fill = "#141414"
foreground = "#ffffff"
opacity = 0.5
padding = 10
radius = 10

[[bar.main.capsule_group]]
id = "controls"
members = ["media", "volume", "session"]
fill = "#141414"
foreground = "#ffffff"
opacity = 0.5
padding = 10
radius = 10
widget_spacing = 4

[wallpaper]
enabled = true
directory = "~/Pictures/wallpapers"

[wallpaper.default]
path = "~/Pictures/wallpapers/02.jpg"

[backdrop]
enabled = true

[lockscreen]
enabled = true
blurred_desktop = false
wallpaper = ""

[idle.behavior.lock]
timeout = 600
action = "lock"
enabled = true

[idle.behavior.screen-off]
timeout = 900
action = "screen_off"
enabled = true

[widget.workspaces]
show_labels = true
label_source = "id"
style = "minimal"
active_pill_size = 2.2
inactive_pill_size = 1.0

[widget.clock]
format = "{:%H:%M}"
font_weight = 700

[widget.volume]
show_label = true

[widget.session]
color = "#ebdbb2"

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

[widget.launcher]
enabled = false
